---
apiVersion: v1
kind: Namespace
metadata: 
  name: ns-game-2048

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: game-2048
  name: deploy-game-2048
  namespace: ns-game-2048
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: game-2048
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: game-2048
    spec:
      containers:
        - name: game-app-2048
          image: public.ecr.aws/repo/game-2048:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: svc-game-2048
spec:
  selector:
    app.kubernetes.io/name: game-2048
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
